--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/nhanaz-pm-pl/BetterCancel
build-by-default: true
branches:
- master
projects:
  BetterCancel:
    path: ""
    libs:
      - src: NhanAZ/libBedrock/libBedrock
        version: 1.0.0
...
